### PR TITLE
Use num_traits.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by netvl** [comment]
Oooh, nice, they split num crate in parts. Thanks!

**Comment by Ms2ger** [comment]
Want to release to crates.io?

**Comment by netvl** [comment]
Probably a bit later.

**Comment by Ms2ger** [comment]
Ping? :)

**Comment by netvl** [comment]
Oh, I'm very sorry! I'm on it right now.

**Comment by netvl** [comment]
Done, v0.3.3 is on crates.io.

**Pull request merged**
