### PR TITLE
updating byteorder dep version

### PR DESCRIPTION
**Pull request by jmr0**

### CODE REVIEW

**Comment by jmr0** [comment]
I'm preparing a PR to address https://github.com/servo/servo/issues/7047 -- wanted to make sure deps were up to date and matched Servo's own. Thanks!

**Comment by netvl** [comment]
Thanks! Sorry for late response, I'm busy with my thesis now :)

**Comment by jmr0** [comment]
@netvl Not a problem! Any chance we could release a new version of immeta with the updated dep? That would allow us to onboard it on Servo. No rush though -- and thanks again.

**Comment by netvl** [comment]
Oh, sorry - I forgot that committing an update and releasing it are different things >_< It is now available as 0.2.3.

I feel honored that Servo depends on my library :)

**Comment by jmr0** [comment]
@netvl figured I'd let you know it finally landed :) https://github.com/servo/servo/pull/9208

**Comment by netvl** [comment]
@jmr0, thanks, that's great!

**Pull request merged**
